In [4]:
import pandas as pd
filename = 'DEBT_data_excel.xlsx'
pd.read_excel(filename).head(5)

,"Government deficit and debt in the EU-countries by function, unit, country and time",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Units: -,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
2,Government EMU-debt,Mill. Euro (current prices),Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
3,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
4,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3

In [5]:
debt = pd.read_excel(filename, skiprows=2)
debt.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Government EMU-debt,Mill. Euro (current prices),Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
1,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
2,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3
3,NaN,NaN,Denmark,93084.0,89464.7,93174.5,89061.4,89394.7,79532.5,71183.3,...,113943.4,117801.4,108532.4,105450.1,105727.0,102597.3,104187.6,131859.7,123539.1,113586.0
4,NaN,NaN,Estonia,315.6,333.4,442.9,489.7,499.9,533.1,628.1,...,1934.2,2129.9,2077.4,2174.1,2174.0,2127.4,2373.4,5094.4,5533.5,6657.4