In [1]:
# autoreload modules when code is run. Otherwise, python will not see recent changes. 
%load_ext autoreload
%autoreload 2

In [25]:
import pandas as pd
filename = 'new_debt_data.xlsx'
pd.read_excel(filename).head(5)

,"Government deficit and debt in the EU-countries by unit, function, country and time",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Units: -,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,2000.0,2001.0,2002.0,2003.0,2004.0,2005.0,2006.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
2,Mill. Euro (current prices),Government EMU-debt,Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
3,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
4,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3

In [26]:
debt = pd.read_excel(filename, skiprows=2)
debt.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Mill. Euro (current prices),Government EMU-debt,Belgium,280959.5,286055.5,288110.8,285866.7,288418.8,294975.3,297494.9,...,414432.4,431384.3,438504.8,451619.9,454048.4,459388.5,467249.4,515211.9,548456.4,578063.2
1,NaN,NaN,Bulgaria,10177.1,10269.8,8890.3,8126.5,7526.2,6388.6,5721.0,...,7147.6,11619.3,11871.6,14188.1,13182.6,12427.2,12311.1,15131.7,17013.2,19352.9
2,NaN,NaN,Cyprus,6024.5,6660.9,7339.8,8184.8,9055.9,9595.9,9597.7,...,18706.5,19013.8,19296.8,19631.5,18935.6,21343.9,21565.9,25388.1,24744.7,23767.3
3,NaN,NaN,Denmark,93084.0,89464.7,93174.5,89061.4,89394.7,79532.5,71183.3,...,113943.4,117801.4,108532.4,105450.1,105727.0,102597.3,104187.6,131859.7,123539.1,113586.0
4,NaN,NaN,Estonia,315.6,333.4,442.9,489.7,499.9,533.1,628.1,...,1934.2,2129.9,2077.4,2174.1,2174.0,2127.4,2373.4,5094.4,5533.5,6657.4

In [27]:
filename_1 = 'gdp_growth.xlsx'
pd.read_excel(filename_1, skiprows= [1, 2, 3, 4, 5, 7,12], sheet_name= 'Sheet 1').head(10)

/Users/darjababan/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Data extracted on 04/04/2024 11:55:20 from [ESTAT],Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,National accounts indicator (ESA 2010),NaN,Gross domestic product at market prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TIME,2012,NaN,2013,NaN,2014,NaN,2015,NaN,2016,...,2019,NaN,2020,NaN,2021,NaN,2022,NaN,2023,NaN
2,GEO (Labels),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,European Union - 27 countries (from 2020),-0.7,NaN,-0.1,NaN,1.6,NaN,2.3,NaN,2,...,1.8,NaN,-5.6,NaN,6,NaN,3.4,NaN,0.4,NaN
4,Euro area – 20 countries (from 2023),-0.9,NaN,-0.2,NaN,1.4,NaN,2,NaN,1.9,...,1.6,NaN,-6.1,NaN,5.9,NaN,3.4,NaN,0.4,NaN
5,Belgium,0.7,NaN,0.5,NaN,1.6,NaN,2,NaN,1.3,...,2.2,NaN,-5.3,NaN,6.9,NaN,3,p,1.3,p
6,Bulgaria,0.7,NaN,-0.5,NaN,0.9,NaN,3.4,NaN,3,...,4,NaN,-4,NaN,7.7,NaN,3.9,NaN,1.8,p
7,Czechia,-0.8,NaN,0,NaN,2.3,NaN,5.4,NaN,2.5,...,3,NaN,-5.5,NaN,3.6,NaN,2.4,NaN,-0.3,NaN
8,Denmark,0.2,NaN,0.9,NaN,1.6,NaN,2.3,NaN,3.2,...,1.5,NaN,-2.4,NaN,6.8,NaN,2.7,NaN,1.8,NaN
9,Germany,0.4,NaN,0.4,NaN,2.2,NaN,1.5,NaN,2.2,...,1.1,p,-3.8,p,3.2,p,1.8,p,-0.3,p

In [ ]:
## data from world bank might be nicer to work with than euro stats! 
## contains gdp growth and gdp per capita growth

In [35]:
filename_world_bank = 'gdp_growth_world_bank.xlsx'
print(pd.read_excel(filename_world_bank).head(10)) 
## TODO REMOVE SERIES CODE AND CHANGE TO LONG FORMAT, PART IN [] SHOULD BE DELETED

             Series Name        Series Code     Country Name Country Code  \
0  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG          Belgium          BEL
1  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG          Croatia          HRV
2  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG           France          FRA
3  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG           Greece          GRC
4  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG       Luxembourg          LUX
5  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG         Portugal          PRT
6  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG  Slovak Republic          SVK
7  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG           Sweden          SWE
8  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG         Slovenia          SVN
9  GDP growth (annual %)  NY.GDP.MKTP.KD.ZG           Poland          POL

   2000 [YR2000]  2001 [YR2001]  2002 [YR2002]  2003 [YR2003]  2004 [YR2004]  \
0       3.716679       1.099619       1.706885       1.037983       3.571204
1       2.956275       3.120864       5.820578       5.599633       4.179949
2       3.923669       1.983721       1.135531       0.823161       2.829753
3       3.919771       4.131612       3.922872       5.794532       5.060992
4       6.938130       3.074355       3.225417       2.619379       4.231891
5       3.816178       1.943672       0.770924      -0.930521       1.788736
6       1.166527       3.253784       4.509444       5.499083       5.278881
7       4.766349       1.449499       2.196921       2.309811       4.336856
8       3.672372       3.216560       3.505598       2.960260       4.359193
9       4.560985       1.258569       2.035863       3.498391       4.982845

   2005 [YR2005]  2006 [YR2006]  2007 [YR2007]  2016 [YR2016]  2017 [YR2017]  \
0       2.321737       2.552350       3.676881       1.266686       1.619580
1       4.307493       5.076835       5.075022       3.562288       3.399574
2       1.663220       2.449324       2.424736       1.095464       2.291420
3       0.599142       5.652434       3.273747      -0.487173       1.092149
4       2.482875       6.016715       8.098668       4.978190       1.317188
5       0.781848       1.625034       2.506580       2.019485       3.506345
6       6.623461       8.493177      10.832029       1.943951       2.938069
7       2.858803       4.662774       3.439222       2.070593       2.567925
8       3.797973       5.746397       6.980161       3.191853       4.815381
9       3.506835       6.131136       7.061535       2.953509       5.140018

   2018 [YR2018]  2019 [YR2019]  2020 [YR2020]  2021 [YR2021]  2022 [YR2022]
0       1.792945       2.240835      -5.260779       6.850996       3.009903
1       2.820323       3.399717      -8.591424      13.784947       6.347115
2       1.865066       1.842972      -7.540459       6.435210       2.454758
3       1.668429       1.879490      -9.316436       8.379944       5.557287
4       1.219322       2.915848      -0.909830       7.168402       1.380186
5       2.849326       2.682760      -8.300517       5.737437       6.827511
6       4.030390       2.511256      -3.335499       4.789146       1.750448
7       1.950023       1.986196      -2.170213       6.147025       2.911772
8       4.454366       3.522679      -4.240884       8.228500       2.460783
9       5.945208       4.449988      -2.020071       6.934980       5.260364